# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPodsFailingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CocoaPodsFailingDemo

  target 'CocoaPodsFailingDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoaPodsFailingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CocoaPodsFailingDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CocoaPodsFailingDemo-tvOS

  target 'CocoaPodsFailingDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
